### ISSUE TITLE
pip install and sub-modules?

### ISSUE THREAD

**Issue by aewallin** [masfaraud/BMSpy#1]
after a "pip install bms" and trying one example I get:
Traceback (most recent call last):
  File "bms_ex1.py", line 9, in <module>
    from bms.signals.functions import Ramp
ImportError: No module named signals.functions

could you please check on a fresh install if the pypi package install works? I suspect the __init__.py files for the submodules need more content.
I am on ubuntu 16.04lts with python 2.7.11

**Comment by masfaraud** [comment]
I would need this 'bms_ex1.py" to have a better idea of the situation.

**Comment by darrell-rg** [comment]
I had this same problem, this is due to the pip install being an older version(0.4 for me).  When i installed from github with setup.py this problem is fixed.

**Comment by masfaraud** [comment]
It should work now, I have reuploaded the package with pip, it should be at version 0.0.6 now.

**Comment by K0ertis** [comment]
Hi! I have installed it with ```pip install bms``` and got the same version. I get with ```pip show bms``` and ```pip3 show bms``` : 
```
 ---
Name: bms
Version: 0.4
Location: /home/alk/.local/lib/python2.7/site-packages
Requires: numpy, matplotlib, networkx
```

I have Ubuntu 15.10

**Comment by K0ertis** [comment]
The same with Ubuntu 16.04:
``` pip3 install bms ```   
```
Collecting bms
  Downloading bms-0.04.tar.gz
```

**Comment by masfaraud** [comment]
Thanks for reporting, I will check ASAP.

**Comment by masfaraud** [comment]
Ok, I think the problem come from the change of versioning number: I changed from 0.04 to 0.0.5 and for pypi the situation is now: 0.04>0.0.7 
I deleted the old versions on pypi, tell me if you still have this problem.
