### ISSUE TITLE
Networkx needs to be < 2.0

### ISSUE THREAD

**Issue by AlexisTM** [masfaraud/BMSpy#10]
Networkx 2.0 removed the reverse argument to the topological sorting.

**Comment by AlexisTM** [comment]
Tested with networkx 1.11 on Python2
```bash
sudo pip install "networkx<2.0"
```

**Comment by AdoHaha** [comment]
I have similar bug, error when running the examples: TypeError: topological_sort() got an unexpected keyword argument 'reverse'

**Comment by AlexisTM** [comment]
@AdoHaha Simply run: 

```
```

**Comment by masfaraud** [comment]
Hi, I have added Networkx dependency as >2.0 and removed the reverse=False argument.
Can you guys the problem is solved?
Thanks!

**Comment by masfaraud** [comment]
Should be fix in v0.1.2
