### ISSUE TITLE
install and plot problems

### ISSUE THREAD

**Issue by waszil** [masfaraud/BMSpy#16]
Hey, this is a great job!!!
I found some problems, however:

- I have python 3.6.4 (Anaconda3), and tried to install this with pip install bms. It got installed, but it is maybe some older version, for example the physical module is not present at all. When I downloaded it from github, and tried to install manually with python setup.py install, the following appeared:

> LookupError: setuptools-scm was unable to detect version for 'c:\\BMSpy-master'.
> Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the
> .git folder) don't contain the necessary metadata and will not work.
> For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
> 

- The other one is just a little thing: the PlotVariables function opened the plot, but then it disappeared instantly. For this I found a solution: plt.show() of fig.show() (in core.py, line 524).

Thanks a lot, and again, great job!

**Comment by masfaraud** [comment]
I see the problem, I have to remove the use of setuptools-scm in the future...
I changed the show as you mentionned.

**Comment by masfaraud** [comment]
Hi, commit https://github.com/masfaraud/BMSpy/commit/4a4b5b148e19e62cdd55d76ca3d8bd685c675bf7 should resolve the install problem.
Can you confirm?

**Comment by masfaraud** [comment]
Drone is not set to ensure these problem don't show again
