### ISSUE TITLE
Can't find Drag and Drop

### ISSUE THREAD

**Issue by montovaneli** [masfaraud/BMSpy#5]
Hello. First of all, you are doing an incredible job here! I hope we can have a fully functional Python "Simulink" one day! I'm an electrical engineering student and also a Python fan.

So, talking about my issue, I've read all the documentation, but I haven't found a way to access the Drag & Drop Model drawer.  Can you help me?

Cheers,
Douglas

**Comment by masfaraud** [comment]
Hi,
You can render the model using `ds.DrawModel` where ds is a DynamicSystem Object.
There is an example in https://github.com/masfaraud/BMSpy/blob/master/examples/electric_motor.py
