### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by ilayn** [masfaraud/BMSpy#7]
Thanks a lot for this exciting project! It really looks very promising. Especially [for my own control systems library](https://github.com/ilayn/harold) I really needed something like this for a long time. Please let me know if you need a hand on the Dynamic System model parts. 

I have to ask though, would you please include the license information or could you clarify which license you have in mind and add it to the repository? 

----
A minor dependency issue : When I run the electric_motor.py example I received the missing module `cma` error. I see that it is missing from the dependency list in the setup.py

**Comment by masfaraud** [comment]
Thanks for your contribution, I added the LGPL license. CMA dependency is removed.

I don't have much time right now to develop actively this library, so if you use it feel free to interact with me, sharing models or ideas for developement!
