### ISSUE TITLE
Pypi package (bms-0.1.0) incomplete

### ISSUE THREAD

**Issue by AlexisTM** [masfaraud/BMSpy#9]
The Pypi package (python 2.7) seems to be "broken"? 

The dependencies are not auto-installing and the `bms/physical` folder do not exist.

You can check it here: https://pypi.python.org/pypi/bms

Isn't it because of the install script?

https://github.com/masfaraud/BMSpy/blob/ddc4ce9278663b29c123d33104c9ff1fc226a0fc/setup.py#L14-L26

The packages line should be:

```python
packages=['bms','bms.blocks','bms.signals','bms.physical'], 
```

**Comment by masfaraud** [comment]
Hi @AlexisTM  I have added your suggestion on master.
Thanks for the reporting.

**Comment by AlexisTM** [comment]
Thanks :)
